image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - centos-pgsql-minimal
  - centos-pgsql-ssl
  - centos-pgsql-contribs
  - ubuntu-pgsql-minimal
  - ubuntu-pgsql-ssl
  - ubuntu-pgsql-contribs

build-centos-pgsql-minimal:
  stage: centos-pgsql-minimal
  script:
    - for i in 90 91 92 93 94 95 96 10 11
    - do
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/centos-pgsql-minimal:v${i}" ./centos-base/pgsql-minimal/pgsql${i}
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/centos-pgsql-minimal:v${i}"
    - done

build-centos-pgsql-ssl:
  stage: centos-pgsql-ssl
  script:
    - for i in 90 91 92 93 94 95 96 10 11
    - do
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/centos-pgsql-ssl:v${i}" ./centos-base/pgsql-ssl/pgsql${i}
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/centos-pgsql-ssl:v${i}"
    - done

build-centos-pgsql-contribs:
  stage: centos-pgsql-contribs
  script:
    - for i in 90 91 92 93 94 95 96 10 11
    - do
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/centos-pgsql-contribs:v${i}" ./centos-base/pgsql-contribs/pgsql${i}
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/centos-pgsql-contribs:v${i}"
    - done

build-ubuntu-pgsql-minimal:
  stage: ubuntu-pgsql-minimal
  script:
    - for i in 90 91 92 93 94 95 96 10 11
    - do
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-pgsql-minimal:v${i}" ./ubuntu-base/pgsql-minimal/pgsql${i}
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-pgsql-minimal:v${i}"
    - done

build-ubuntu-pgsql-ssld:
  stage: ubuntu-pgsql-ssl
  script:
    - for i in 90 91 92 93 94 95 96 10 11
    - do
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-pgsql-ssl:v${i}" ./ubuntu-base/pgsql-ssl/pgsql${i}
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-pgsql-ssl:v${i}"
    - done

build-ubuntu-pgsql-contribs:
  stage: ubuntu-pgsql-contribs
  script:
    - for i in 90 91 92 93 94 95 96 10 11
    - do
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-pgsql-contribs:v${i}" ./ubuntu-base/pgsql-contribs/pgsql${i}
    - docker push "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/ubuntu-pgsql-contribs:v${i}"
    - done
