name: Build PostgreSQL Container Image

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build-centos-base-pgsql-minimal:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-push-master
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: checkout-pull-request
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build pgsql-minimal (CentOS base)
      run: |
        for i in 96 10 11 12 13 14; do
        docker build -t "centos-pgsql-minimal:v${i}" ./centos-base/pgsql-minimal/pgsql${i}
        done
        docker image prune -f
        docker image ls

  build-centos-base-pgsql-ssl:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-push-master
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: checkout-pull-request
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build pgsql-ssl (CentOS base)
      run: |
        for i in 96 10 11 12 13 14; do
        docker build -t "centos-pgsql-ssl:v${i}" ./centos-base/pgsql-ssl/pgsql${i}
        done
        docker image prune -f
        docker image ls

  build-centos-base-pgsql-contribs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-push-master
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: checkout-pull-request
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build pgsql-contribs (CentOS base)
      run: |
        for i in 96 10 11 12 13 14; do
        docker build -t "centos-pgsql-contribs:v${i}" ./centos-base/pgsql-contribs/pgsql${i}
        done
        docker image prune -f
        docker image ls

  build-ubuntu-base-pgsql-minimal:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-push-master
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: checkout-pull-request
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build pgsql-minimal (Ubuntu base)
      run: |
        for i in 96 10 11 12 13 14; do
        docker build -t "ubuntu-pgsql-minimal:v${i}" ./ubuntu-base/pgsql-minimal/pgsql${i}
        done
        docker image prune -f
        docker image ls

  build-ubuntu-base-pgsql-ssl:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-push-master
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: checkout-pull-request
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build pgsql-ssl (Ubuntu base)
      run: |
        for i in 96 10 11 12 13 14; do
        docker build -t "ubuntu-pgsql-ssl:v${i}" ./ubuntu-base/pgsql-ssl/pgsql${i}
        done
        docker image prune -f
        docker image ls

  build-ubuntu-base-pgsql-contribs:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-push-master
      if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        ref: master
    - name: checkout-pull-request
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Build pgsql-contribs (Ubuntu base)
      run: |
        for i in 96 10 11 12 13 14; do
        docker build -t "ubuntu-pgsql-contribs:v${i}" ./ubuntu-base/pgsql-contribs/pgsql${i}
        done
        docker image prune -f
        docker image ls
